[theme]
primaryColor = "#2193b0"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
base = "light"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
magicEnabled = true
fastReruns = true
